# Q-Learning with Table for FrozenLake-v0
reference: https://medium.com/emergent-future/simple-reinforcement-learning-with-tensorflow-part-0-q-learning-with-tables-and-neural-networks-d195264329d0

In [9]:
import gym
import numpy as np

In [10]:
env = gym.make('FrozenLake-v0')

[2017-05-08 11:39:48,232] Making new env: FrozenLake-v0


## update Q-table

In [38]:
#Initialize table with all zeros
Q = np.zeros([env.observation_space.n,env.action_space.n])
# Set learning parameters
lr = .85
y = .99
num_episodes = 10000
#create lists to contain total rewards and steps per episode
#jList = []
rList = []


In [39]:
for i in range(num_episodes):
    #Reset environment and get first new observation
    s = env.reset()
    rAll = 0
    d = False
    j = 0
    #The Q-Table learning algorithm
    while j < 99:
        j+=1
        #Choose an action by greedily (with noise) picking from Q table
        a = np.argmax(Q[s,:] + np.random.randn(1,env.action_space.n)*(1./(i+1)))
        #Get new state and reward from environment
        s1,r,d,_ = env.step(a)
        #Update Q-Table with new knowledge with bellman equation
        Q[s,a] = Q[s,a] + lr*(r + y*np.max(Q[s1,:]) - Q[s,a])
        rAll += r
        s = s1
        if d == True:
            break
    #jList.append(j)
    rList.append(rAll)


In [40]:
print("Score over time: " +  str(sum(rList)/num_episodes))

Score over time: 0.5215


In [41]:
print("Final Q-Table Values")
print(Q)

Final Q-Table Values
[[  9.73949251e-03   3.18607412e-03   7.65363301e-01   9.85365037e-03]
 [  2.28950743e-03   1.11720646e-03   5.72683756e-06   4.20643773e-01]
 [  2.18088195e-03   0.00000000e+00   7.59818230e-03   2.80693599e-01]
 [  8.98472267e-04   1.39558761e-04   1.17480407e-03   1.99176033e-01]
 [  7.80777541e-01   0.00000000e+00   5.25918692e-04   1.05388409e-03]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  6.37532930e-03   6.64094275e-11   1.37147790e-04   1.95230204e-05]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  2.08374804e-04   7.65538639e-04   1.61710656e-04   3.79326836e-01]
 [  1.50270609e-03   7.77696689e-01   5.16492099e-04   7.61590091e-04]
 [  1.53289332e-01   8.49627907e-05   6.51942152e-05   1.06569609e-04]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  1.08116546e-04   4.26611423e-03   7.03065109e-01   0

## Test Agent

In [64]:
def testAgent():
    s = env.reset()
    d = False
    j=0
    while j < 99999:
        j+=1
        #env.render() #uncomment this line to show the game simulator
        #Choose an action by greedily (with noise) picking from Q table
        a = np.argmax(Q[s,:])
        #Get new state and reward from environment
        s1,r,d,_ = env.step(a)
        #Update Q-Table with new knowledge
        Q[s,a] = Q[s,a] + lr*(r + y*np.max(Q[s1,:]) - Q[s,a])
        s = s1
        if d == True:
            #s1-current state
            #r-reward. 0-fall into hole; 1-find the destination
            #d-done. true-done; false-fail;
            #print(s1, r, d)
            break
    return r

In [72]:
rewards = []
for i in range(1000):
    r = testAgent()
    rewards.append(r)
    score = sum(rewards)/1000
print(score)

0.543
