# Introduction to Unsupervised Learning and K-means Algorithm
> In this notebook, it will show you Unsupervised Learning algorithm "K-means".

> 1.What is Unsupervised Learning?

> 2.Brief of K-means Algorithm?

> 3.Implementaion of K-means Algorithm with SK-learn

> 4.Break it down

### 1.What is Unsupervised Learning?
Unsupervised Learning Algorithm is **Clustering Algorithm** which has only the dataset without labels.

Below image show the application of Unsupervised Learning Algorithm:


<img src="asset/Unsupervised_learning.png",width=500,height=500, style="float: left;">

### 2.Brief of K-means Algorithm?
http://scikit-learn.org/stable/modules/clustering.html#overview-of-clustering-methods

The KMeans algorithm clusters data by trying to separate samples in n groups of equal variance, minimizing a criterion known as the inertia or within-cluster sum-of-squares.

K-means is hill climbing algorithm, which its result really depends on where you put your inital cluster center points.

There are 2 inputs for K-means: K(number of cluster), training set{x1,x2,...,xn}.

The algorithm will mainly do 2 things:
1. Randomly initilize K cluster centroid;
2. Optimize to minimize the total quadratic distance;


<img src="asset/k-mean1.png",width=400,height=400, style="float: left;">

<img src="asset/k-mean2.png",width=400,height=400, style="float: left;">



### 3.Implementaion of K-means Algorithm with SK-learn

In [20]:
from sklearn.cluster import KMeans
import numpy as np

X = np.array([[1, 2], [1, 4], [1, 0], [4, 2], [4, 4], [4, 0]])
kmeans = KMeans(n_clusters=2, random_state=0).fit(X)

In [19]:
kmeans.labels_

array([0, 0, 0, 1, 1, 1], dtype=int32)

In [17]:
kmeans.predict([[0, 0], [4, 4]])

array([0, 1], dtype=int32)

In [18]:
kmeans.cluster_centers_

array([[ 1.,  2.],
       [ 4.,  2.]])

### 4.Break it down
* Unsupervised Learning Algorithm is Clustering Algorithm which has only the dataset without labels.
* K-Means first randomly initilize K cluster centroid; then optimize to minimize the total quadratic distance;